// <auto-generated />
using FullStackApplication.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace FullStackApplication.Migrations
{
    [DbContext(typeof(VectorDbContext))]
    [Migration("20260210092147_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FullStackApplication.Models.Entities.DadJoke", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Joke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jokes");
                });

            modelBuilder.Entity("FullStackApplication.Models.Entities.DadJokeEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DadJokeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.HasKey("Id");

                    b.HasIndex("DadJokeId")
                        .IsUnique();

                    b.ToTable("Embeddings");
                });

            modelBuilder.Entity("FullStackApplication.Models.Entities.DadJokeEmbedding", b =>
                {
                    b.HasOne("FullStackApplication.Models.Entities.DadJoke", "Joke")
                        .WithOne("Embedding")
                        .HasForeignKey("FullStackApplication.Models.Entities.DadJokeEmbedding", "DadJokeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joke");
                });

            modelBuilder.Entity("FullStackApplication.Models.Entities.DadJoke", b =>
                {
                    b.Navigation("Embedding");
                });
#pragma warning restore 612, 618
        }
    }
}
